### ISSUE TITLE
Button to download both at the same time

### ISSUE THREAD

**Issue by randoomdude** [rcc11/4chan-sounds-player#11]
There are buttons for quick image download and the music itself but what about one if you want to download two files in one click?
![image](https://user-images.githubusercontent.com/6027132/158002083-6af07801-f29a-414f-a03e-7be09514ef58.png)

**Comment by rcc11** [comment]
@randoomdude You can call functions of the sound player in templates using `@<event>`, like below. Replace "Download Both" with whatever content you want for the button.
```html
<a href="#" class="fcsp-col-auto" @click='tools.download("sound-image", "sound-filename");tools.download("sound-src", "sound-name"):prevent'>
	Download Both
</a>
```

The click handler for the button calls [tools.download](https://github.com/rcc11/4chan-sounds-player/blob/master/src/components/tools/download.js#L81-L96) for both the image and the sound. The `sound-<prop>` arguments get replaced with values for the currently playing sound. It's not ideal though because in some case the arguments will need escaping and that's not possible to do in the template. I'll try to add that as an improvement, but this should cover almost all cases for now.

The player uses [bootstrap icons](https://icons.getbootstrap.com/) so I'd recommend replacing "Download Both" with the svg for whichever icon you like there. Here's a good choice.
```html
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
	<path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293V6.5z"/>
	<path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
</svg>
```

**Comment by rcc11** [comment]
@randoomdude You can call functions of the sound player in templates using `@<event>`, like below. Replace "Download Both" with whatever content you want for the button.
```html
<a href="#" class="fcsp-col-auto" @click='tools.download("sound-image", "sound-filename");tools.download("sound-src", "sound-name"):prevent'>
	Download Both
</a>
```

The click handler for the button calls [tools.download](https://github.com/rcc11/4chan-sounds-player/blob/master/src/components/tools/download.js#L81-L96) for both the image and the sound. The `sound-<prop>` arguments get replaced with values for the currently playing sound. It's not ideal though because in some case the arguments will need escaping and that's not possible to do in the template. I'll try to add that as an improvement, but this should cover almost all cases for now.

The player uses [bootstrap icons](https://icons.getbootstrap.com/) so I'd recommend replacing "Download Both" with the svg for whichever icon you like there. Here's a good choice.
```html
<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
	<path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293V6.5z"/>
	<path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
</svg>
```

**Comment by rcc11** [comment]
Updated for the event attribute changes. Assuming this button goes in the footer template.
```html
<a href="#" class="fcsp-col-auto" @click.prevent="tools.download('sound-image-esc', 'sound-filename-esc');tools.download('sound-src-esc', 'sound-name-esc')">
	<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-file-earmark-arrow-down" viewBox="0 0 16 16">
		<path d="M8.5 6.5a.5.5 0 0 0-1 0v3.793L6.354 9.146a.5.5 0 1 0-.708.708l2 2a.5.5 0 0 0 .708 0l2-2a.5.5 0 0 0-.708-.708L8.5 10.293V6.5z"/>
		<path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
	</svg>
</a>
```

**Comment by randoomdude** [comment]
How do I implement the above code? I pasted it into both footer and Custom CSS and I don't see anything change?
![image](https://user-images.githubusercontent.com/6027132/189803215-5dd3ca5e-eced-4faa-8835-2f0126b5f77d.png)

**Comment by randoomdude** [comment]
Semi related to this, although it's a bit of a stretch if this is implementable but i'll suggest it anyway, make a way to log files you downloaded previously so that it doesn't download the same songs when you do the download all batch
